"""Add name column to User

Revision ID: 436e6815f1d9
Revises: 1a0e0463d81a
Create Date: 2024-12-23 17:27:47.100238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '436e6815f1d9'
down_revision = '1a0e0463d81a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
